### PR TITLE
Add thano rules into rbac

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
https://github.com/helm/charts/commit/347d7a627be3a695c6500926bad888e9887a2c66#diff-3aa210e2fed854e7e981213b8dce54a0  https://github.com/rancher/rancher/issues/26969#issuecomment-629565133

**Comment by StrongMonkey** [comment]
cc @ekristen

**Comment by ekristen** [comment]
Are these needed? I'm not clear why they are in the prometheus operator. The thanos rulers are suppose to be created on the thanos-ruler service to be executed by thanos-ruler against thanos-query and stored back against the thanos-store.

I don't think it hurts anything being here, but not sure the motivation by prometheus operator to include them when prometheus operator doesn't do a thanos deployment just the sidecar deployment.

**Comment by StrongMonkey** [comment]
Yeah I think it is not necessary since it was working before. But the misleading log on the prometheus-operator seems to confuse users.

**Review by deniseschannon — APPROVED** [review]

**Pull request merged**
