### PR TITLE
Update external-dns deployment api version

### PR DESCRIPTION
**Pull request by guangbochen**
Update the external-dns deployment API version to `apps/v1` to make it compatible with k8s v1.16 upgrade.

**Related Issue:**
https://github.com/rancher/rancher/issues/21768

### CODE REVIEW

**Comment by loganhz** [comment]
LGTM

**Comment by cjellick** [comment]
does this depend on any other PRs or is it stand alone?

**Comment by guangbochen** [comment]
This is a stand-alone PR for external-dns chart to make it compatible with k8s v1.16 API changes.

**Comment by cjellick** [comment]
lgtm

**Pull request merged**
