### PR TITLE
Refactor monitoring deploying

### PR DESCRIPTION
**Pull request by thxCode**
**Problem:**
- Previous charts cannot satisfy the `project-level` monitoring deploying design
- Grafana cannot be restarted after password changed
- `node-exporter` cannot be scheduled to `controlpane` or `etcd` role nodes
- Prometheus cannot be started with PVC that provided by some storage provisioner which don't respect the `SecurityContext`

**Solution:**
- Deploy `project-level` monitoring with a permission-limit Prometheus
- Remove Grafana account `Secret` and use provisioning instead of `grafana-watch`
- Modify `node-exporter` taints
- Add configurable `SecurityContext` for Prometheus and Alertmanager

**Issue:**
- rancher/rancher#17039
- rancher/rancher#16962
- rancher/rancher#17030
- rancher/rancher#17256

**Related PR:**
- https://github.com/rancher/prometheus-auth/pull/2

### CODE REVIEW

**Comment by guangbochen** [comment]
LGTM

**Comment by guangbochen** [comment]
LGTM of the chart, need to test upgrading on the rancher server side.

**Comment by thxCode** [comment]
Based on this PR, Monitoring can support some new parameters:
- `exporter-kubelets.https` should be false when deploying in GKE. Default is `true`.
- `exporter-node.collectors.xxxx` adaptes [node_exporter#v0.17.0 Linux OS type collector](https://github.com/prometheus/node_exporter#collectors). Default is `{}`. For example:

```yaml
// disable collecting ARP
exporter-node.collectors.arp.enabled=false

 // enable collecting WIFI
exporter-node.collectors.wifi.enabled=true

 // enable collecting textfile (by default) and indicate to /var/run/something.prom
exporter-node.collectors.textfile.enabled=true
exporter-node.collectors.textfile.directory=/var/run/something.prom
```
- `exporter-node.enabledHostNetwork` detectes using `hostNetwork` or not, if disabling, node_exporter cannot collect the real network traffic in host. Default is `true`.
- `exporter-node.enabledHostPID` detectes using `hostPID` or not, if disabling, node_exporter cannot collect the real filesystem situation in host. Default is `true`.

@loganhz

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
