### PR TITLE
[2.4] Set rancher max version to 2.4.4 for monitoring v0.1.0

### PR DESCRIPTION
**Pull request by daanemanz**

### CODE REVIEW

**Comment by daanemanz** [comment]
Closes https://github.com/rancher/rancher/issues/27672

**Review by armsnyder — APPROVED** [review]

**Comment by cbron** [comment]
Fixed with: https://github.com/rancher/system-charts/pull/260

**Comment by daanemanz** [comment]
Thanks for the quick fix @cbron.

**Comment by cbron** [comment]
No problem, thanks for letting us know!

**Pull request closed without merging**
