### PR TITLE
[2.4] updated fluentd containers to use the latest rancher image

### PR DESCRIPTION
**Pull request by paynejacob**

### CODE REVIEW

**Comment by nickgerace** [comment]
Slightly unrelated, do we need backports for the tolerations and nodeselector changes to this chart?

**Review by nickgerace — DISMISSED** [review]

**Comment by brendarearden** [comment]
When adding system charts, there should be at least two separate commits. The first commit should be just a base copy of the existing chart, and then the second commit would be the changes for the new version. It makes it easier to quickly see the changes from the previous version. Ex: https://github.com/rancher/system-charts/pull/265/commits - please update your pr to follow this flow

**Review by nickgerace — APPROVED** [review]

**Review by brendarearden — APPROVED** [review]
lgtm

**Comment by paynejacob** [comment]
This is waiting on a fluentd release

**Comment by paynejacob** [comment]
This is stale and not needed

**Pull request closed without merging**
