### PR TITLE
Delete rancher-gke-operator

### PR DESCRIPTION
**Pull request by cmurphy**
rancher-gke-operator has moved to feature charts for 2.6.

### CODE REVIEW

**Review by cbron — COMMENTED** [review]
lgtm, but wait for Ricky to confirm this plan before we do it

**Review by thedadams — APPROVED** [review]

**Comment by rmweir** [comment]
I think this should be fine, we need to do it for the other operators too.

**Review by rmweir — APPROVED** [review]
LGTM, comment above.

**Review by cbron — APPROVED** [review]
Happens for other operators here: https://github.com/rancher/system-charts/pull/505/files

**Pull request merged**
