### PR TITLE
[forwardport] Add eks-operator 1.0.1000

### PR DESCRIPTION
**Pull request by thedadams**
Original PR:
https://github.com/rancher/system-charts/pull/493

### CODE REVIEW

**Comment by jiaqiluo** [comment]
@thedadams  I am confused about the version. 

In [dev-v2.6](https://github.com/rancher/system-charts/tree/dev-v2.6/charts/rancher-eks-operator), we already have `1.0.100` and `1.1.100`, and now you are adding `1.0.1000`?

**Review by jiaqiluo — CHANGES_REQUESTED** [review]
@thedadams  I am confused about the version. 

In [dev-v2.6](https://github.com/rancher/system-charts/tree/dev-v2.6/charts/rancher-eks-operator), we already have `1.0.100` and `1.1.100`, and now you are adding `1.0.1000`?

**Comment by thedadams** [comment]
@jiaqiluo Yes, that's correct. Version `1.1.100` will be removed soon. I am adding version `1.0.1000` to `dev-v2.5`, so it needs to be here as well.

**Review by jiaqiluo — APPROVED** [review]
LGTM

**Comment by cbron** [comment]
Think we decided not to do this anymore, depending on what Ricky finds out

**Comment by thedadams** [comment]
We decided not to do this.

**Pull request closed without merging**
