### PR TITLE
[2.4] add the missing rules for exporter-kube-state

### PR DESCRIPTION
**Pull request by jiaqiluo**
https://github.com/rancher/rancher/issues/27748

In monitroing `v0.1.1`, the new image `rancher/coreos-kube-state-metrics:v1.9.5` for Workload `exporter-kube-state-cluster-monitoring` ask for listing/watching the following resouces:

```
  "volumeattachments" in API group "storage.k8s.io" at the cluster scope 
  "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope 
  "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope 
  "networkpolicies" in API group "networking.k8s.io" at the cluster scope 
```

### CODE REVIEW

**Comment by deniseschannon** [comment]
@jiaqiluo Since we've already shipped v0.1.1, we can't make changes to an existing chart. You need to base copy to a new template as 1 commit and then make a second commit with your changes between the templates.

**Comment by AcidAngel21** [comment]
`mutatingwebhookconfigurations` in API group `admissionregistration.k8s.io` is missing in your commit.

**Review by AcidAngel21 — COMMENTED** [review]
`mutatingwebhookconfigurations` in API group `admissionregistration.k8s.io`  is missing.

**Comment by jiaqiluo** [comment]
new PR is made here: https://github.com/rancher/system-charts/pull/273

**Pull request closed without merging**
