### PR TITLE
WIP: Support upgrading Monitoring from catalog app page

### PR DESCRIPTION
**Pull request by thxCode**
- Adjust the operator into sub-charts dir to fix https://github.com/rancher/rancher/issues/18578

### CODE REVIEW

**Comment by orangedeng** [comment]
Do you have the issue for `Add new permission to kube-state exporter`? Please file one for QA

**Comment by thxCode** [comment]
@orangedeng  updated

**Comment by orangedeng** [comment]
LGTM

**Comment by thxCode** [comment]
Fixing is including in https://github.com/rancher/system-charts/pull/36, close this.

**Pull request closed without merging**
