### PR TITLE
Add Monitoring v0.1.4

### PR DESCRIPTION
**Pull request by aiyengar2**
Related Issues: https://github.com/rancher/rancher/issues/27253, https://github.com/rancher/rancher/issues/29290

### CODE REVIEW

**Review by mrajashree — DISMISSED** [review]

**Comment by aiyengar2** [comment]
@deniseschannon since [v0.1.3 is already in `release/v2.4`](https://github.com/rancher/system-charts/tree/release-v2.4/charts/rancher-monitoring/v0.1.3), does this PR need to have a base copy -> v0.1.4?

Not sure if we need a new chart for this since 
1) it's a small change 
2) it's just introducing a previously unsettable field (see https://github.com/rancher/rancher/pull/29478) that would not have impacted anyone who is currently using monitoring (since, if they were impacted, they wouldn't have been able to successfully deploy monitoring in the first place)
3) anyone who needs this feature such as the person who opened up this ticket would anyways be installing / reinstalling monitoring to use it.

If we want to be safe, it should be easy to make the change though.

**Comment by aiyengar2** [comment]
Also, the changes to this chart will have no effect unless https://github.com/rancher/rancher/pull/29478 is merged since any values supplied to `operator-init` (like this newly exposed value) would be ignored by `operatorHandler` (i.e. the Rancher controller that actually handles the logic for deploying the CRDs + the Prometheus Operator pod) either way till that change goes in.

**Comment by dramich** [comment]
@aiyengar2 Yes, it needs to be a new version, we are making changes to something that is already released.

**Comment by aiyengar2** [comment]
> @aiyengar2 Yes, it needs to be a new version, we are making changes to something that is already released.

Updated!

**Comment by aiyengar2** [comment]
> @aiyengar2 Yes, it needs to be a new version, we are making changes to something that is already released.

Since we're releasing a new version with this PR, I slightly modified the purpose of this PR to address both https://github.com/rancher/rancher/issues/27253 and https://github.com/rancher/rancher/issues/29290 since they are both minor changes.

Merging this PR should be blocked based on resolving https://github.com/rancherlabs/eio/issues/280 and ensuring that the new prometheus-auth image exists on DockerHub. 

But no code changes will be introduced after that so this PR is still ready for review.

**Review by pennyscissors — APPROVED** [review]
lgtm

**Review by dramich — APPROVED** [review]

**Comment by aiyengar2** [comment]
> Merging this PR should be blocked based on resolving [rancherlabs/eio#280](https://github.com/rancherlabs/eio/issues/280) and ensuring that the new prometheus-auth image exists on DockerHub.

https://hub.docker.com/layers/rancher/prometheus-auth/v0.2.1/images/sha256-b8d21dad8923689177c526ab0291d30e22180a754b0b3ca8eb67dd142063c87a?context=explore exists

**Pull request merged**
