### PR TITLE
Changes needed to use new security-scan image

### PR DESCRIPTION
**Pull request by prachidamle**
Adding a new version to the CIS chart to publish the new security-scan tag v0.1.12

### CODE REVIEW

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Comment by leodotcloud** [comment]
We don't need a new chart version, just updating the image version in the existing one is enough.

**Review by leodotcloud — CHANGES_REQUESTED** [review]
Please see previous comment.

**Comment by prachidamle** [comment]
@leodotcloud we have already released the previous version in 2.4.5 release, hence changing the version 
cc @deniseschannon pls let me know if we can keep the version same if there is no upgrade impact

**Review by leodotcloud — APPROVED** [review]

**Comment by leodotcloud** [comment]
Denise's comments:
we should always add a new system chart if any changes have existed
and increase the version
I understand that this chart is different, but it should follow the same paradigm of the other charts

**Review by dramich — APPROVED** [review]

**Pull request merged**
