### PR TITLE
Modify images to rancher official

### PR DESCRIPTION
**Pull request by thxCode**
| docker.io/quay.io official | rancher alias |
| --- | --- |
| quay.io/coreos/prometheus-operator:v0.26.0 | rancher/coreos-prometheus-operator:v0.26.0 |
| quay.io/coreos/prometheus-config-reloader:v0.26.0 | rancher/coreos-prometheus-config-reloader:v0.26.0 |
| quay.io/coreos/configmap-reload:v0.0.1 | rancher/coreos-configmap-reload:v0.0.1 |
| prom/node-exporter:v0.17.0 | rancher/node-exporter:v0.17.0 |
| quay.io/coreos/kube-state-metrics:v1.4.0 | rancher/coreos-kube-state-metrics:v1.4.0 |
| prom/alertmanager:v0.15.2 | rancher/prom-alertmanager:v0.15.2 |
| grafana/grafana:5.3.0 | rancher/grafana:5.3.0 |
| nginx:1.15.8-alpine | rancher/nginx:1.15.8-alpine |
| prom/prometheus:v2.5.0 | rancher/prometheus:v2.5.0 |

### CODE REVIEW

**Comment by alena1108** [comment]
@thxCode @loganhz all images are pushed

**Comment by loganhz** [comment]
@alena1108 Thanks! We will test it first, then we can merge this PR

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/16810

**Comment by loganhz** [comment]
LGTM, tested

**Comment by orangedeng** [comment]
@loganhz @alena1108 I think we should following the pattern of what we did for `prom/` prefix in https://github.com/rancher/types/blob/master/image/mirror.go#L21. So `prom/prometheus` should be `rancher/prom-prometheus`.

**Comment by loganhz** [comment]
@orangedeng we will address it after 2.2

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
