### PR TITLE
Add RKE2 to CIS Benchmark

### PR DESCRIPTION
**Pull request by briandowns**
Adds necessary components to be able to run security-scan for RKE2.

### CODE REVIEW

**Comment by prachidamle** [comment]
@briandowns LGTM, but maybe can you just rename the first commit to mention "Basecopy...", maybe refer previous version addition commits

**Comment by briandowns** [comment]
> @briandowns LGTM, but maybe can you just rename the first commit to mention "Basecopy...", maybe refer previous version addition commits

Complete @prachidamle . Thanks!

**Review by prachidamle — APPROVED** [review]
LGTM

**Review by cbron — APPROVED** [review]

**Comment by briandowns** [comment]
Issue for reference: https://github.com/rancher/rke2/issues/1

**Pull request merged**
