### PR TITLE
Add rancher-k3s-upgrade 0.3.1

### PR DESCRIPTION
**Pull request by thedadams**
Related issues:
https://github.com/rancher/rancher/issues/34908
https://github.com/rancher/rancher/issues/34908

### CODE REVIEW

**Review by kinarashah — COMMENTED** [review]
@thedadams could we split the commits, one for base copy 0.3.0 and a new commit for 0.3.1 that updates the version? makes it easier to review + debug the diffs later on

**Comment by thedadams** [comment]
@kinarashah I think I did that. Copied the 0.3.0 directory to 0.3.1 in one commit. Then bumped all the versions in the second.

**Comment by kinarashah** [comment]
@thedadams Ah, I see now that they got under the suc bump commit. So the content is fine, we just need to edit the commit msgs. 1) Base copy rancher-k3s-upgrade 0.3.0 2) bump k3s-upgrade to 0.3.1 and suc to 0.8.0-rc.1

**Comment by thedadams** [comment]
@kinarashah Sorry about that. I updated the messages.

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
