### PR TITLE
Fix Monitoring bugs

### PR DESCRIPTION
**Pull request by thxCode**
- Upgrade to v0.0.3
- Fix
  + rancher/rancher#19693
  + rancher/rancher#18830
  + rancher/rancher#19243
  + rancher/rancher#19689
  + rancher/rancher#19410
  + rancher/rancher#19248

### CODE REVIEW

**Comment by orangedeng** [comment]
For the scrape interval, I would prefer to use 30s for all the service to keep consistency. I would like to have some more information about this change.

**Comment by thxCode** [comment]
@orangedeng , The rate to scrape is using global interval, the default is 60s. Give two options to configure the global intervals:
- `prometheus.scrapeInterval`
- `prometheus.evaluationInterval`

Mark the Operator default setting: https://github.com/coreos/prometheus-operator/blob/cd293ac33bd0def8c271b78dbff1a8d88df06eee/pkg/prometheus/promcfg.go#L150-L158

**Comment by orangedeng** [comment]
LGTM

**Comment by alena1108** [comment]
@thxCode can the commits be squashed (commit1 - base copy, commit2 - changes), or are they logically separate?

**Comment by thxCode** [comment]
@alena1108  squashed.

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/19673

**Pull request merged**
