### PR TITLE
[2.3] Update rancher max version to 2.4.4 for monitoring v0.1.0

### PR DESCRIPTION
**Pull request by nikkelma**

### CODE REVIEW

**Comment by dramich** [comment]
Closing as duplicate of https://github.com/rancher/system-charts/pull/260

**Comment by nikkelma** [comment]
Edited the base branch, sorry for the confusion

**Comment by cbron** [comment]
We shouldn't need this as in the system-charts 2.3 branch the 0.1.1 chart is min of 2.3.8-rc1

**Comment by nikkelma** [comment]
This is why we have different branches per minor version - thank you!

**Pull request closed without merging**
