### PR TITLE
Update monitoring/Istio chart for k8s v1.16 compatibility

### PR DESCRIPTION
**Pull request by gitlawr**
Issue: https://github.com/rancher/rancher/issues/22488

1. Update for API group migration

Note:
See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
PSP is introduced in policy apigroup in 1.10, and removed from extensions apigroup in 1.16.
DaemonSet, Deployment, StatefulSet, and ReplicaSet migrate to apps in 1.9, and no longer be served from extensions in 1.16.

2. Update Prometheus operator to v0.32.0

- Bump Prometheus operator image version
- Add a new CRD PodMonitor
- Update ClusterRole

This PR depent on the following image mirroring:
```
quay.io/coreos/prometheus-operator:v0.32.0 => rancher/coreos-prometheus-operator:v0.32.0
quay.io/coreos/prometheus-config-reloader:v0.32.0 => rancher/coreos-prometheus-config-reloader:v0.32.0
```

### CODE REVIEW

**Review by orangedeng — APPROVED** [review]

**Comment by orangedeng** [comment]
LGTM

**Comment by gitlawr** [comment]
Updated API group in RBAC resources

**Comment by guangbochen** [comment]
I think we also need to consider aligning the following change regards the upstream [prometheus-operator](https://github.com/helm/charts/commits/master?before=46d5a6fa8683d52c9c6fae35d85daca443f2817a+70&path%5B%5D=stable&path%5B%5D=prometheus-operator&path%5B%5D=Chart.yaml) chart:
- https://github.com/helm/charts/commit/6a94c082c2daf8be72ac241397d652993ad82a0b#diff-3aa210e2fed854e7e981213b8dce54a0R51
- https://github.com/helm/charts/commit/eba702c8303610d330b859040669351867d8a646#diff-b9f481ac97524bfb24d27f62676dc143
- https://github.com/helm/charts/commit/9fa4db5f3f2981fc56d5e54b9f551a9c86fdfbe0#diff-b9f481ac97524bfb24d27f62676dc143
- https://github.com/helm/charts/commit/90e50f1e08fe5a7603f07a457a4d7dd885e6dd5f#diff-23b6255dfa711af76ad99181e2fb0464L273
- bump kube-state-metrics image to v1.7.2 & node-exporter to v0.18.1 respectively (optional)
   -  https://github.com/helm/charts/commit/af2af1af669f0fe2f72bbf0c736831f00f38f315#diff-83a474e9876689d2e21429a0440263efL4

You may double-check the commits before `077132c` at [upstream chart](https://github.com/helm/charts/commits/master?after=b7b9e6270e2ada175247026511ad50d2266cfeb6+34&path%5B%5D=stable&path%5B%5D=prometheus-operator&path%5B%5D=Chart.yaml) to decide whether we need to sync them or not.

**Comment by gitlawr** [comment]
Those commits are basically operator chart improvements and seem to be beyond the scope of this PR. So I would rather not take them in. 
By the way, what is the workflow we've used to sync upstream updates?

**Comment by cbron** [comment]
On that note, can we be sure that new prometheus operator works with [our current CRD's](https://github.com/rancher/system-charts/tree/dc835997a365e2318679d9efdb15e79f8d10fc36/charts/rancher-monitoring/v0.0.4/charts/operator-init/files) like alert-manager or service-monitor ?

**Comment by gitlawr** [comment]
Discussed with @guangbochen and we think that we should pick upstream changes for RBAC and CRDs to align with Prometheus operator v0.32.0

**Review by guangbochen — APPROVED** [review]
LGTM

**Comment by gitlawr** [comment]
@cbron For the CRD updates, There's no field changes in alertmanager/servicemonitor. There are new fields added in prometheus/prometheusrule. and several Thanos specific fields dropped in prometheus. They are not used/configurable in the chart, so it will be fine for upgrade.

**Review by cjellick — APPROVED** [review]

**Pull request merged**
