### PR TITLE
Monitoring v0.1.1

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
Fix https://github.com/rancher/rancher/issues/26969

**Comment by StrongMonkey** [comment]
Include https://github.com/rancher/system-charts/pull/185

**Review by guangbochen — COMMENTED** [review]
LGTM of the template changes, since we have bumped the prometheus-operator images, a very important thing to verify is that the CRDs are also updated to the newer version of existing deployment, otherwise prometheus-operator may encounter some incompatible error due to CRD changes.

**Review by thxCode — APPROVED** [review]
LGTM, agree with @guangbochen.

**Pull request merged**
