### PR TITLE
Add resources quota to Grafana

### PR DESCRIPTION
**Pull request by thxCode**
**Problem:**
Can't enable project level monitoring without resources quota

**Solution:**
Add resource quota to workload spec

**Issue:**
https://github.com/rancher/rancher/issues/16993

### CODE REVIEW

**Comment by thxCode** [comment]
@loganhz , @orangedeng

**Comment by loganhz** [comment]
@guangbochen Can you help to review it, please?

**Comment by guangbochen** [comment]
LGTM.

**Comment by guangbochen** [comment]
LGTM.

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
